name: 'test_dbt'
version: '1.0.0'
config-version: 2

profile: 'test_dbt'

model-paths: ["models"]
analysis-paths: ["analysis"]
seed-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
log-path: /tmp/

target-path: "/tmp/target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  test_dbt:
    example:
      +materialized: view